---
title: "dNBR Annual for Larch Forest"
author: "Anna Talucci"
date: "5/23/2023"
output: html_document
---

# Overview
The code in this script can be copied into Earth Engine to produce dNBR images for the Larch forest across eastern Siberia.

In EE, the data is processed by fire perimeters and year to remain within the computational limits of EE.
    
This script is adapted from previous scripts used to map fires in eastern Siberia by Talucci et al. (2022).

Below are five chunks of JavaScript code. The code within the chunk can be copied and pasted into the EE code editor. 

For Chunk #1, Please note the fire perimeters are available for download from the [Arctic Data Center](https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2GB1XJ4M)

For Chunk #2, several lines of code are turned off, with only a few turned on to stay within the computational limits. Each variable is either run by itself or in conjunction with one other. This sub-setting was required to remain within the computational limitations of EE. The image processing is run on a single fire season. For 2011-2020, the single fire year is subset further by splinting up the perimeters into smaller groups with the property `IDobj` for the region that contains the Eastern Siberia Taiga (EST), Taimyr-Central Siberian Tundra (TCST), Trans-Baikal Bald Mountain tundra (TBBMT).


In Chunk #3, define the `aoi` to match what is run in Chunk #2.

In chunk #4, we process the imagery, where dNBR is calculated from one-year pre-fire and one-year post-fire. Additionally, the imagery is exported in this chunk, and the file's name will need to be changed for each run.

Each run produces a single output for a given year, and `aoi` results in 55 image outputs. 

# Chunk 1
This defines the pre-fir year, year of fire, and post-fire year. These years will need to be changed to iterate through the 2001-2020 fire years. This chunk also calls in the fire perimeters, which can be downloaded from the Arctic Data Center. Finally, we create two lists with the EcoCode Names for the areas relevant to the project. These lists are used to subset the data in Chunk 2, which allowed us to remain within EE computational limits.

```{js}
// Center Map
Map.setCenter(160.092, 66.704, 4);

// changes years for specific fire year year***************************************************
var pre = '2019' //Year prefire
var year = '2020' //Fire year
var post = '2021'//Year postfire


// Fire perimeters
var fc = ee.FeatureCollection("users/actalucci/FLARE-Fires/SiberiaFires2001-2020")

// List of EcoCode for subsetting data to stay within computational limits
var lis1 = ee.List(['NST', 'CKMT', 'BT']);
var lis2 = ee.List(['EST', 'TCST', 'TBBMT']);
```

# Chunk 2
This chunk of code contains many components that are used separately for a given year and location to remain within the computational limits of EE. For all years, iterate through variable `fc_ne`. For variable `fc_e`, run years 2001-2010 on the entire `fc_e` area. For 2011-2020, `fc_e` needs to be split into smaller groups to stay within the computational limits, which involve running the `fc_e` variable plus either `fe_e1_YYYY`, `fc_e2_YYYY`, or `fc_e3_YYYY`.

The code is currently set up to run the fire year 2020 for east2, `fc_e2_2020`.


```{js}
// var fc_all = fc.filter("FireYr == 2001");// **change year** 
// var fc_ne = fc.filter(ee.Filter.inList('EcoCode', lis1)).filter("FireYr == 2020") // **change year **
var fc_e = fc.filter(ee.Filter.inList('EcoCode', lis2)).filter("FireYr == 2020") // **change year **

// Split East into two groups for 2011-2020 (to stay within computational limits)
// iterate through each line individually

// var fc_e1_2011 = fc_e.filter(ee.Filter.lessThanOrEquals('IDobj', 4363)) // **Turn on/off depending on Year **
// var fc_e2_2011 = fc_e.filter(ee.Filter.greaterThan('IDobj', 4363)) // **Turn on/off depending on Year **

// var fc_e1_2012 = fc_e.filter(ee.Filter.lessThanOrEquals('IDobj', 3611.5)) // **Turn on/off depending on Year **
// var fc_e2_2012 = fc_e.filter(ee.Filter.greaterThan('IDobj', 3611.5)) // **Turn on/off depending on Year **

// var fc_e1_2013 = fc_e.filter(ee.Filter.lessThanOrEquals('IDobj', 3466)) // **Turn on/off depending on Year **
// var fc_e2_2013 = fc_e.filter(ee.Filter.greaterThan('IDobj', 3466)) // **Turn on/off depending on Year **

// var fc_e1_2014 = fc_e.filter(ee.Filter.lessThanOrEquals('IDobj', 3975)) // **Turn on/off depending on Year **
// var fc_e2_2014 = fc_e.filter(ee.Filter.greaterThan('IDobj', 3975)) // **Turn on/off depending on Year **

// var fc_e1_2015 = fc_e.filter(ee.Filter.lessThanOrEquals('IDobj', 3159)) // **Turn on/off depending on Year **
// var fc_e2_2015 = fc_e.filter(ee.Filter.greaterThan('IDobj', 3159)) // **Turn on/off depending on Year **

// var fc_e1_2016 = fc_e.filter(ee.Filter.lessThanOrEquals('IDobj', 2717)) // **Turn on/off depending on Year **
// var fc_e3_2016 = fc_e.filter(ee.Filter.and(ee.Filter.greaterThan('IDobj', 2717), ee.Filter.lessThan('IDobj', 4976))) // **Turn on/off depending on Year **
// var fc_e2_2016 = fc_e.filter(ee.Filter.greaterThan('IDobj', 3980)) // **Turn on/off depending on Year **

// var fc_e1_2017 = fc_e.filter(ee.Filter.lessThanOrEquals('IDobj', 1762)) // **Turn on/off depending on Year **
// var fc_e2_2017 = fc_e.filter(ee.Filter.and(ee.Filter.greaterThan('IDobj', 1762), ee.Filter.lessThan('IDobj', 4976))) // **Turn on/off depending on Year **
// var fc_e3_2017 = fc_e.filter(ee.Filter.greaterThan('IDobj', 4976)) // **Turn on/off depending on Year **


// var fc_e1_2018 = fc_e.filter(ee.Filter.lessThanOrEquals('IDobj', 2603)) // **Turn on/off depending on Year **
// var fc_e2_2018 = fc_e.filter(ee.Filter.and(ee.Filter.greaterThan('IDobj', 2603), ee.Filter.lessThan('IDobj', 5269))) // **Turn on/off depending on Year **
// var fc_e3_2018 = fc_e.filter(ee.Filter.greaterThanOrEquals('IDobj', 5269)) // T**Turn on/off depending on Year **

// var fc_e1_2019 = fc_e.filter(ee.Filter.lessThanOrEquals('IDobj', 2389)) // **Turn on/off depending on Year **
// var fc_e2_2019 = fc_e.filter(ee.Filter.and(ee.Filter.greaterThan('IDobj', 2389), ee.Filter.lessThan('IDobj', 4906))) // **Turn on/off depending on Year **
// var fc_e3_2019 = fc_e.filter(ee.Filter.greaterThanOrEquals('IDobj', 4906)) // **Turn on/off depending on Year **

// var fc_e1_2020 = fc_e.filter(ee.Filter.lessThanOrEquals('IDobj', 4713)) // **Turn on/off depending on Year **
var fc_e2_2020 = fc_e.filter(ee.Filter.and(ee.Filter.greaterThan('IDobj', 4713), ee.Filter.lessThan('IDobj', 6159))) // **Turn on/off depending on Year **
// var fc_e3_2020 = fc_e.filter(ee.Filter.greaterThanOrEquals('IDobj', 6159)) // **Turn on/off depending on Year **
```

# Chunk 3
Here, we define the `aoi`, and make sure the `aoi` is defined as the variable run in Chunk 2.



```{js}
print(fc_e.size())
// print(fc_e1_2016.size())
// print(fc_e2_2016.size())


// Define AOI (switch on/off depending on above lines and Change Year)
// var aoi = fc_e1_2020 // **SWITCH & CHANGE YEAR**
var aoi = fc_e2_2020 // **SWITCH & CHANGE YEAR**
// var aoi = fc_e3_2020 // **SWITCH & CHANGE YEAR**
// var aoi = fc_e // **SWITCH & CHANGE YEAR**
// var aoi = fc_ne // **SWITCH & CHANGE YEAR**

// Add layers to map
// Map.addLayer(fc_all, {}, 'all')
Map.addLayer(aoi, {}, 'aoi')
```

# Chunk 4
This chunk processes the imagery for the aoi defined above, including calculating dNBR and masking out areas that do not have larch. 


```{js}
// Function to mask outside polygons
var maskOutside = function(image, fc) {
  var mask = ee.Image.constant(1).clip(fc).mask()
  return image.updateMask(mask)
}
// Larch forest mask
var larch = ee.Image('users/ewebb/masks/mask_'+year)

Map.addLayer(larch, {}, 'larch')

// Projection Equal Area (https://spatialreference.org/ref/sr-org/albers-equal-area-russia/)
var proj = ee.Projection('PROJCS["Albers Conical Equal Area",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9108"]],AUTHORITY["EPSG","4326"]],PROJECTION["Albers_Conic_Equal_Area"],PARAMETER["standard_parallel_1",50],PARAMETER["standard_parallel_2",70],PARAMETER["latitude_of_center",56],PARAMETER["longitude_of_center",100],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["meters",1]]').atScale(10000)


// VISUALIZATION PARAMETERS 
var viz = {min: -0.1, max: 1, palette: ['00FFFF', '0000FF']};
var dnbrViz = {min: -100, max: 1500, palette: ['7CFC00', 'FFFF00', 'FFA500', 'FF0000']};
var vizParams = {bands: ['B5', 'B4', 'B3'], min: 0, max: 0.5, gamma: [0.95, 1.1, 1] };

// ################################################################
// ### FUNCTIONS ###
// ################################################################

// Define coefficients supplied by Roy et al. (2016) for translating ETM+
// surface reflectance to OLI surface reflectance.
var coefficients = {
  itcps: ee.Image.constant([0.0003, 0.0088, 0.0061, 0.0412, 0.0254, 0.0172]).multiply(10000),
  slopes: ee.Image.constant([0.8474, 0.8483, 0.9047, 0.8462, 0.8937, 0.9071])
};

// Define function to get and rename bands of interest from OLI.
function renameOLI(img) {
  return img.select(
		['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'pixel_qa'],
		['Blue', 'Green', 'Red', 'NIR', 'SWIR1', 'SWIR2', 'pixel_qa']
	);
}

// Define function to get and rename bands of interest from ETM+.
function renameETM(img) {
  return img.select(
		['B1', 'B2', 'B3', 'B4', 'B5', 'B7', 'pixel_qa'],
		['Blue', 'Green', 'Red', 'NIR', 'SWIR1', 'SWIR2', 'pixel_qa']
  );
}

// Define function to apply harmonization transformation.
function etm2oli(img) {
  return img.select(['Blue', 'Green', 'Red', 'NIR', 'SWIR1', 'SWIR2'])
    .multiply(coefficients.slopes)
    .add(coefficients.itcps)
    .round()
    .toShort()
    .addBands(img.select('pixel_qa')
  );
}

// Define function to mask out clouds and cloud shadows.
function fmask(img) {
  var cloudShadowBitMask = 1 << 3;
  var cloudsBitMask = 1 << 5;
  var waterBitMask = 1 << 2;
  var snowBitMask = 1 << 4;
  var qa = img.select('pixel_qa');
  var mask = qa.bitwiseAnd(cloudShadowBitMask).eq(0)
    .and(qa.bitwiseAnd(cloudsBitMask).eq(0)
    .and(qa.bitwiseAnd(waterBitMask).eq(0)
    .and(qa.bitwiseAnd(snowBitMask).eq(0))));
  return img.updateMask(mask);
}

// Define function to calculate NBR.
function calcNBR(img) {
  return img.normalizedDifference(['NIR', 'SWIR2']).rename('nbr');
}

// Define function to prepare OLI images.
function prepOLI(img) {
  var orig = img;
  img = renameOLI(img);
  img = fmask(img);
  img = calcNBR(img);
  return ee.Image(img.copyProperties(orig, orig.propertyNames()));
}

// Define function to prepare ETM+ images.
function prepETM(img) {
  var orig = img;
  img = renameETM(img);
  img = fmask(img);
  img = etm2oli(img);
  img = calcNBR(img);
  return ee.Image(img.copyProperties(orig, orig.propertyNames()));
}

// ################################################################
// ### APPLICATION ###
// ################################################################

// Display AOI on the map.
// Map.centerObject(aoi, 10);
// Map.addLayer(aoi, {color: 'f8766d'}, 'AOI');
// Map.setOptions('HYBRID');

// Get Landsat surface reflectance collections for OLI, ETM+ and TM sensors.
var oliCol = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR');
var etmCol= ee.ImageCollection('LANDSAT/LE07/C01/T1_SR');
var tmCol= ee.ImageCollection('LANDSAT/LT05/C01/T1_SR');

// Define a collection filter.
var colFilter = ee.Filter.and(
  ee.Filter.bounds(aoi),
  ee.Filter.date(pre+'-05-01', post+'-08-30'),
    ee.Filter.lt('CLOUD_COVER', 50),
  ee.Filter.lt('GEOMETRIC_RMSE_MODEL', 10),
  ee.Filter.or(
    ee.Filter.eq('IMAGE_QUALITY', 9),
    ee.Filter.eq('IMAGE_QUALITY_OLI', 9)
  )
);

// Filter collections and prepare them for merging.
oliCol = oliCol.filter(colFilter).map(prepOLI);
etmCol= etmCol.filter(colFilter).map(prepETM);
tmCol= tmCol.filter(colFilter).map(prepETM);

// Merge the collections.
var ls_full = oliCol
  .merge(etmCol)
  .merge(tmCol);

// Pre and Post fire imagery
var prefire = ee.ImageCollection(ls_full.filterDate(pre+'-05-01', pre+'-08-30').filterBounds(aoi).sort('CLOUD_COVER_LAND')),
    postfire = ee.ImageCollection(ls_full.filterDate(post+'-05-01', post+'-08-30').filterBounds(aoi).sort('CLOUD_COVER_LAND'));


var nbr = ee.ImageCollection(ls_full.filterDate(year + '-05-01', year + '-08-30').filterBounds(aoi).sort('CLOUD_COVER_LAND')).median().select('nbr').multiply(1000)
 
// Generate a annual composite 
var q_prefire = prefire.qualityMosaic('nbr').select('nbr').multiply(1000),
    q_postfire = postfire.qualityMosaic('nbr').select('nbr').multiply(1000);


// Calculate dNBR      
var dnbr = q_prefire.subtract(q_postfire).select('nbr')
var dnbr_masked = dnbr.mask(larch).clip(aoi)

// Add Layer to Map
// Map.addLayer(dnbr, dnbrViz, 'dnbr')
Map.addLayer(dnbr_masked, dnbrViz, 'dnbr_masked')

// Map.addLayer(fc, {}, 'fc')
```

# Chunk 5
This chunk exports the dNBR image to assets. The file name should be changed for each iteration. Anything associated with the aoi `fc_ne` is considered to be Northeastern Siberia, including ecozones Northeast Siberia Taiga (NST), Cherskii–Kolyma mountain tundra (CKMT), and Bering Tunda (BT). For anything associated with the aoi `fc_e`, this is considered eastern Siberia, including ecozones Eastern Siberia Taiga (EST), Taimyr-Central Siberian Tundra (TCST), Trans-Baikal Bald Mountain tundra (TBBMT). For additional subsets of `fc_e`, add a 1, 2, or 3, depending on the `aoi`.

```{js}
//------------------------- EXPORT TO ASSET --------------------------------------//
// Export the image to an Earth Engine asset.
Export.image.toAsset({
  image: dnbr_masked,
  description:'east2_dnbr_'+year, //**CHANGE NAME with AOI**
  assetId:"projects/ee-flare-treemortality-dnbr/assets/east2_dnbr_"+year,//**CHANGE NAME with AOI**
  scale: 30,
  crs: proj.wkt().getInfo(),
  region: aoi,
  maxPixels: 1e13
});
```


# References
Talucci, A. C., M. M. Loranty, and H. D. Alexander. 2022. Siberian taiga and tundra fire regimes from 2001–2020. Environmental Research Letters 17:025001.
